version: "3.8"

services:
  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8001"
    ports:
      - "80:80"
      - "8001:8001"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      
  graph-service:
    build:
      context: ./GraphService
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.graph-service.rule=Path(`/graph`)"
      - "traefik.http.routers.graph-service.entrypoints=web"
      
  bfs-service:
    build:
      context: ./BFSService
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bfs-service.rule=Path(`/bfs`)"
      - "traefik.http.routers.bfs-service.entrypoints=web"
      
  edmonds-karp-service:
    build:
      context: ./EdmondsKarpService
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.edmonds-karp-service.rule=Path(`/edmondsKarpMaxGraphFlow`)"
      - "traefik.http.routers.edmonds-karp-service.entrypoints=web"
      
  push-relabel-service:
    build:
      context: ./PushRelabelService
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.push-relabel-service.rule=Path(`/pushRelabelMaxGraphFlow`)"
      - "traefik.http.routers.push-relabel-service.entrypoints=web"