version: "3.8"

networks:
  traefikee_ingress:
    external: true

services:
  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8001"
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "80:80"
      - "8001:8001"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      
  graph-service:
    image: weronikapiotrowska/java-graph-service
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.graph-service.rule=Path(`/graph`)"
        - "traefik.http.routers.graph-service.entrypoints=web"
        - "traefik.http.services.graph-service.loadbalancer.server.port=80"
    networks:
      - traefikee_ingress

  bfs-service:
    image: weronikapiotrowska/java-bfs-service
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bfs-service.rule=Path(`/bfs`)"
        - "traefik.http.routers.bfs-service.entrypoints=web"
        - "traefik.http.services.bfs-service.loadbalancer.server.port=80"
    networks:
      - traefikee_ingress

  edmonds-karp-service:
    image: weronikapiotrowska/java-edmonds-karp-service
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.edmonds-karp-service.rule=Path(`/edmondsKarpMaxGraphFlow`)"
        - "traefik.http.routers.edmonds-karp-service.entrypoints=web"
        - "traefik.http.services.edmonds-karp-service.loadbalancer.server.port=80"
    networks:
      - traefikee_ingress

  push-relabel-service:
    image: weronikapiotrowska/java-push-relabel-service
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.push-relabel-service.rule=Path(`/pushRelabelMaxGraphFlow`)"
        - "traefik.http.routers.push-relabel-service.entrypoints=web"
        - "traefik.http.services.push-relabel-service.loadbalancer.server.port=80"
    networks:
      - traefikee_ingress