version: "3.8"

services:
  graph-service:
    build:
      context: ./GraphService
      
  bfs-service:
    build:
      context: ./BFSService
      
  edmonds-karp-service:
    build:
      context: ./EdmondsKarpService

  push-relabel-service:
    build:
      context: ./PushRelabelService
      
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8001:80