server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: edmonds-karp-service
          uri: lb://EDMONDS-KARP-SERVICE
          predicates:
            - Path=/graphs/edmondsKarpMaxFlow/**
        - id: push-relabel-service
          uri: lb://PUSH-RELABEL-SERVICE
          predicates:
            - Path=/graphs/pushRelabelMaxFlow/**
        - id: graph-service
          uri: lb://GRAPH-SERVICE
          predicates:
            - Path=/graphs/**