server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: edmonds-karp-service
          uri: lb://EDMONDS-KARP-SERVICE
          predicates:
            - Path=/edmondsKarpMaxGraphFlow/**
        - id: push-relabel-service
          uri: lb://PUSH-RELABEL-SERVICE
          predicates:
            - Path=/pushRelabelMaxGraphFlow/**
        - id: graph-service
          uri: lb://GRAPH-SERVICE
          predicates:
            - Path=/graph/**,/directedGraph/**